Settings:
  # runtime 类属性 计时器的重置间隔
  runtimeResetPeriod: 60
  # 当 attr-damage 内 isClear|clear|c 参数为true时
  # 不清除的属性
  clearAttributeWhiteList:
    - '生命力'
    - '生命上限'

# 以下选项需重启生效
TempData:
  # 检测间隔 (分钟)
  taskPeriod: 30
  # 玩家离线后
  # 若指定时间内未登录则清除临时数据
  # 单位: 分钟
  timeout: 30
  # 临时属性检测间隔 (tick)
  # 数值过大可能会导致属性无法及时清除
  # 数值过小可能火导致数据量极大时占用过高
  # 异步检测 不会影响主线程
  attributeChecker: 20