name: Atziluth
main: me.mkbaka.atziluth.taboolib.platform.BukkitPlugin
version: ${version}

authors:
  - 'Mkbakaa'

softdepend:
  - 'AttributePlus'
  - 'SX-Attribute'
  - 'OriginAttribute'
  - 'MythicMobs'
  - 'PlaceholderAPI'

api-version: 1.13
